### ISSUE TITLE
roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch miss use or malfunction

### ISSUE THREAD

**Issue by wonwon0** [JenniferBuehler/jaco-arm-pkgs#11]
Hi,

Thank you for your work, it is very help full!

I followed your tutorial on both Kinetic and Jade and encountered the same issue.

When I call 

$ roslaunch jaco_on_table jaco_on_table_gazebo.launch

gazebo launches with the message:

auto-starting new master
process[master]: started with pid [75742]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 660eaf7a-3b3d-11e7-be79-000c29df71f8
process[rosout-1]: started with pid [75755]
started core service [/rosout]
process[gazebo-2]: started with pid [75765]
process[gazebo_gui-3]: started with pid [75775]
process[urdf_spawner-4]: started with pid [75785]
[ INFO] [1495052056.121886229]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1495052056.122879854]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1495052056.472461454, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1495052056.544991599, 0.081000000]: Physics dynamic reconfigure ready.
[urdf_spawner-4] process has finished cleanly
log file: /home/phil/.ros/log/660eaf7a-3b3d-11e7-be79-000c29df71f8/urdf_spawner-4*.log

One odd thing compared to your tutorial is that the robot doesn't have the same colours as in your tutorial (all white on Jade and all black on Kinetic), but it is not the main issue.

When I go on with the 
$ roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch

which displays the message:

auto-starting new master
process[master]: started with pid [76372]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 016e02cc-3b3e-11e7-9ff4-000c29df71f8
process[rosout-1]: started with pid [76385]
started core service [/rosout]
process[gazebo-2]: started with pid [76401]
process[gazebo_gui-3]: started with pid [76408]
process[urdf_spawner-4]: started with pid [76419]
process[robot_state_publisher-5]: started with pid [76420]
[ INFO] [1495052316.902714999]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1495052316.903913344]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1495052317.337042070, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1495052317.638801684, 0.112000000]: Physics dynamic reconfigure ready.
[urdf_spawner-4] process has finished cleanly
log file: /home/phil/.ros/log/016e02cc-3b3e-11e7-9ff4-000c29df71f8/urdf_spawner-4*.log

The robots appears already collapsed.

It is to be noted that I had to implement the fix around line 125 in the GazeboJointControl.cpp

physics::JointControllerPtr _modelJointController = _parent->GetJointController(); (out of scope)

in order to run catkin_make on the project.

**Comment by JenniferBuehler** [comment]
Hi,

thanks for reporting this. I haven't tried this code with kinetic yet, but I was going to do this in the next few days, or latest next week. I will have to test and apply the fix in the joint controller as well, which has been hanging around for a while. I'm just pretty busy so didn't get around to it yet... I can look into your issue when I finally do it in the next days as well.

So the collapsing of the robot happens both in Jade and in Kinetic? And which version of Gazebo are you using - the same in both Jade and Kinetic?

The colour issue could mean that the material ("black", I think) is not found. Again, this could be related to that you are using a different Gazebo version. I will try to test it with the same version you have.

Cheers
Jenny

**Comment by wonwon0** [comment]
Thank you for the (very quick) answer!

I use gazebo 7 on kinetic and gazebo 5 on jade.

The collapsing happens on both setups. The colors are different  on either gazebo 5 or 7 (respectively white and black).

I forgot to mention that I also had to set -std=c++11 in order to compile the project on Kinetic (ubuntu 16.04), while I didn't do it on Jade (ubuntu 14.04).

Once again, thank you for your help!

Philippe

**Comment by JenniferBuehler** [comment]
Hi Philippe,

Ok, thanks for the info. I will let you know here as soon as I have started looking into it.

Jenny

**Comment by JenniferBuehler** [comment]
I've applied some changes to fix the issue with _modelJointController (which you probably got from [joint-control-pkgs issue #2](https://github.com/JenniferBuehler/joint-control-pkgs/issues/2)), in the repository [joint_control_pkgs](https://github.com/JenniferBuehler/joint-control-pkgs). Your plugin probably crashed because you may have forgotten to check ``(_modelJointController!=nullptr)`` later when it is used?

Anyway, as I described in the other issue, this was not the correct solution. Can you pull joint-control-pkgs again, recompile and see if you still have the issue now?

I'm onto the colour issue next, I'm getting the same problem.

**Comment by wonwon0** [comment]
Ho wow, this is really quick! I'll check this out tomorrow (in about 10 hours) when I'm able to access my computer.

**Comment by JenniferBuehler** [comment]
The colour was a problem I actually encountered before. Unfortunately "wildcards" don't work for ``<gazebo>`` tags, at least not in newer versions...

I've changed it to contain the materials for the links explicitly. So if you also pull a new version of this repo now, it should (hopefully) all work.

Let me know if not, or if you run into any other issues.

Cheers
Jenny

**Comment by cangjiaxaun** [comment]
Hi, Jennifer I start to work with the jaco-gazebo simulation on kinetic since last week. I think I meet the same problem. My gazebo version is 7.

**Comment by JenniferBuehler** [comment]
Did you pull the newest version? It should be fixed now.

**Comment by cangjiaxaun** [comment]
The newest version works! But on my system I should manually set the GAZEBO_PLUGIN_PATH to ~/catkin_ws/devel/lib to let gazebo know where to find the plugin. Thank you Jenny!

**Comment by JenniferBuehler** [comment]
Great that it works... strange about the plugin path, I've never had to do this, but it makes sense... Anyway, good that it works!

**Comment by JenniferBuehler** [comment]
@wonwon0 Does it work now for you as well, with the updated version of joint-control-pkgs? If yes, you may close the issue :)

**Comment by wonwon0** [comment]
I'm testing it right now, colors are good but the arm is still collapsed. Maybe it's an error on my side. I haven't tested it yet on jade, only kinetic.

EDIT: I tried to make it run, but i failed. Could it be because I'm running Kinetic on a Vm?

**Comment by JenniferBuehler** [comment]
Hmmm weird that it collapses, I'm using Kinetic too and it works.

Can you send me the command line output please?

I never tried to run ROS/Gazebo on VMs, have you had other issues with it?

**Comment by wonwon0** [comment]
Allright! I made it run on a conventionnal ubuntu 16.04 install (not a VM). Every thing is fine. Really nice! 

I havent been able to circle out the cause of the bug on my vm install.

I'll close this issue and open an other one if i can't manage to figure it out by myself.

In either case, I'll keep you updated and, if you want and I manage to install it on my vm, write a small tutorial to install it if the solution to do so is a little funky.

Thanks a lot for your help!

Philippe

**Comment by JenniferBuehler** [comment]
Great! Thanks for letting me know. Sure, if you manage to get it running in a VM, I'd be interested which changes are required to make it work :) And tutorials are always great.
