### ISSUE TITLE
Adding an object to the gazebo controlled world

### ISSUE THREAD

**Issue by sritee** [JenniferBuehler/jaco-arm-pkgs#13]
How do we add, say a sphere to the world, so while running roslaunch jaco_gazebocontrolled.launch, this sphere shows up. I tried modifying the default world in the jaco_gazebo_controlled.launch file, but this doesn't work and throws up some errors. Thanks!

**Comment by JenniferBuehler** [comment]
You spawn a model from the launch file, e.g.

``<node name="spawn_my_robot" pkg="gazebo_ros" type="spawn_model" args="-file $(find your-package)/urdf/YOUR-MODEL.urdf -urdf -model NAME-OF-YOUR-MODEL" />``

Or you could use another world file in which you have your model. Is that what you did? Which errors were they?

**Comment by sritee** [comment]
What I did was go to the jaco_on_table_gazebo_controlled.launch, opened it, and changed the default launch file <arg name="gazebo_world_file" default="/worlds/empty.world"/> in that to ~/catkin/my_needed_world.world . After investigatinga bit, this file seems to call jaco_gazebo, which in turn calls emptyworld.launch (default file). Do I need to make any other changes? I always only see the empty world come up. Btw great work with the package, finding it really useful :)

**Comment by sritee** [comment]
Fixed by going to jaco_on_table.launch  and changing default value to /myworld.world.

**Comment by JenniferBuehler** [comment]
You could also try

``roslaunch jaco_on_table_gazebo_controlled.launch gazebo_world_file:=<path-to-your-worldfile>``

instead.
