### ISSUE TITLE
xacro Parameters

### ISSUE THREAD

**Issue by HailinRen** [JenniferBuehler/jaco-arm-pkgs#15]
Hi! When I tried to run gym-testing.py using python3, I got this error. Could you help fix it?

jaco-arm-pkgs/jaco_tutorial/jaco_on_table/launch/jaco_on_table_gazebo_controlled.launch

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/xacro/xacro", line 33, in <module>
    xacro.main()
  File "<string>", line 697, in main
  File "<string>", line 627, in eval_self_contained
  File "<string>", line 552, in eval_all
xacro.XacroException: Parameters [robot_components_namespace,trajectory_param_namespace] were not set for macro xacro:gzplugin_joint_control

Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro '/home/rmlab4/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/jaco-arm-pkgs/jaco_tutorial/jaco_on_table/urdf/jaco_on_table_robot_gazebo_ctrl.urdf.xacro' sensor_on_table:=false          use_ros_control:=true          load_grasp_fix:=false          add_transmission_pos:=true         add_transmission_vel:=false         trajectory_param_namespace:=jaco_trajectory         robot_components_namespace:=jaco] returned with code [1].

**Comment by JenniferBuehler** [comment]
How are you launching it? Are you doing
``roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch``?

Not sure about the gym-testing.py, is that your own python script?

As the error description says, the xacro requires parameters ``robot_components_namespace`` and ``trajectory_param_namespace``, which should be set as ROS parameters... could you launch the file, and after it crashed, send me the output of ``rosparam list``?

**Comment by JenniferBuehler** [comment]
Sorry I remembered this wrong, just checked and it's actually set in the launch file:

```xml
                                                                                
  # if the xacro file (robot_xacro) needs additional arguments to xacro.py, put them in here. 
  <arg name="xacro_arguments" default="sensor_on_table:=false                   
    use_ros_control:=$(arg load_ros_controllers)                                
    load_grasp_fix:=$(arg load_grasp_fix)                                       
    add_transmission_pos:=$(arg transmission_pos)                               
    add_transmission_vel:=$(arg transmission_vel)                               
    trajectory_param_namespace:=jaco_trajectory                                 
    robot_components_namespace:=jaco"/>    
```

that's the last two parameters. Then later on the xacro arguments are passed to loading the xacro:

```xml
  #####################################                                         
  # Load robot_description on parameter server                                  
  #####################################                                         
  <param name="robot_description" command="$(find xacro)/xacro --inorder '$(arg robot_xacro)' $(arg xacro_arguments)"/>
```

So if you are using roslaunch, it should work...

**Comment by HailinRen** [comment]
I think we need delete "--inorder" in the following line,
`<param name="robot_description" command="$(find xacro)/xacro --inorder '$(arg robot_xacro)' $(arg xacro_arguments)"/>` 
But I got following fatal error,
`er for 9 joints.
[ INFO] [1522329538.496499676, 0.356000000]: Action server for Joint Trajectory started. Using position mode: 1
[ INFO] [1522329538.496518924, 0.356000000]: Joint trajectory action server running.
[FATAL] [1522329538.497895403, 0.357000000]: Only support 1 axis
gzserver: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
[urdf_spawner-4] process has finished cleanly
log file: /home/rmlab4/.ros/log/bbb6faa4-3353-11e8-93eb-484d7ef21bf9/urdf_spawner-4*.log
Aborted (core dumped)
[gazebo-2] process has died [pid 16054, exit code 134, cmd /home/rmlab4/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -e ode -s libgazebo_world_plugin_loader.so worlds/empty.world __name:=gazebo __log:=/home/rmlab4/.ros/log/bbb6faa4-3353-11e8-93eb-484d7ef21bf9/gazebo-2.log].
log file: /home/rmlab4/.ros/log/bbb6faa4-3353-11e8-93eb-484d7ef21bf9/gazebo-2*.log
`

**Comment by JenniferBuehler** [comment]
Ok, thanks for letting me know. This issue is new in kinetic, I'm just about to re-test all the stuff for kinetic. This issue is related to issue #16 as you already have +1'ed ;) So I will be commenting on it there. I hope I'll be able to get around to it over Easter. Cheers!

**Comment by HailinRen** [comment]
And could you have a look at this " jaco-arm-pkgs/jaco_tutorial/jaco_on_table/urdf/jaco_on_table_robot_gazebo_ctrl.urdf.xacro
"
`And could you have a look at this " jaco-arm-pkgs/jaco_tutorial/jaco_on_table/urdf/jaco_on_table_robot_gazebo_ctrl.urdf.xacro
"<xacro:if value="$(arg use_ros_control)">
        <xacro:include filename="$(find jaco_gazebo)/urdf/gzplugin_ros_control.urdf.xacro"/>
        <xacro:gzplugin_joint_control/>
</xacro:if>
`
I think we need specify the name space when use gzplugin_joint_control, right?
Thank you!

**Comment by JenniferBuehler** [comment]
Hi, so as discussed in #16 the issue should hopefully be fixed now.

As for your other question: not sure I understand what you mean, which namespace, the ROS namespace?

**Comment by JenniferBuehler** [comment]
Since I haven't heard back in a while, I presume this has been resolved. I will close this now. Please re-open if required.
