### ISSUE TITLE
Cannot load the model with joint controllers

### ISSUE THREAD

**Issue by YaqiXie** [JenniferBuehler/jaco-arm-pkgs#16]
When I try to load the model with joint controllers with commend `roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch` , the following error occurs:

(py2_ros) user@user:~/catkin_ws$ roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch
... logging to /home/user/.ros/log/2f184b26-3311-11e8-ba25-484d7ea4dbcf/roslaunch-user-1415.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://user:32909/

SUMMARY
========

PARAMETERS
 * /gazebo/load_velocity_controllers: True
 * /jaco/arm_joint_init: [4.5532045, 4.550...
 * /jaco/arm_joint_max_force: [8, 8, 4, 2, 2, 2]
 * /jaco/arm_joint_max_vel: [0.8, 0.8, 0.8, 0...
 * /jaco/arm_joints: ['jaco_arm_0_join...
 * /jaco/arm_links: ['jaco_0_baseA', ...
 * /jaco/arm_position_controller_names: ['jaco_arm_0_join...
 * /jaco/arm_velocity_controller_names: ['jaco_arm_0_join...
 * /jaco/effector_link: jaco_6_hand_limb
 * /jaco/gazebo_use_set_velocity: True
 * /jaco/gripper_joint_init: [0, 0, 0]
 * /jaco/gripper_joint_max_force: [2, 2, 2]
 * /jaco/gripper_joint_max_vel: [0.3, 0.3, 0.3]
 * /jaco/gripper_joints: ['jaco_finger_joi...
 * /jaco/gripper_links: ['jaco_fingers_ba...
 * /jaco/gripper_position_controller_names: ['jaco_finger_joi...
 * /jaco/gripper_velocity_controller_names: ['jaco_finger_joi...
 * /jaco/jaco_arm_0_joint_position_controller/joint: jaco_arm_0_joint
 * /jaco/jaco_arm_0_joint_position_controller/pid/d: 0
 * /jaco/jaco_arm_0_joint_position_controller/pid/i: 1.0
 * /jaco/jaco_arm_0_joint_position_controller/pid/p: 20
 * /jaco/jaco_arm_0_joint_position_controller/type: position_controll...
 * /jaco/jaco_arm_0_joint_velocity_controller/joint: jaco_arm_0_joint
 * /jaco/jaco_arm_0_joint_velocity_controller/pid/d: 0
 * /jaco/jaco_arm_0_joint_velocity_controller/pid/i: 0
 * /jaco/jaco_arm_0_joint_velocity_controller/pid/p: 0.4
 * /jaco/jaco_arm_0_joint_velocity_controller/type: velocity_controll...
 * /jaco/jaco_arm_1_joint_position_controller/joint: jaco_arm_1_joint
 * /jaco/jaco_arm_1_joint_position_controller/pid/d: 0
 * /jaco/jaco_arm_1_joint_position_controller/pid/i: 1.0
 * /jaco/jaco_arm_1_joint_position_controller/pid/p: 20
 * /jaco/jaco_arm_1_joint_position_controller/type: position_controll...
 * /jaco/jaco_arm_1_joint_velocity_controller/joint: jaco_arm_1_joint
 * /jaco/jaco_arm_1_joint_velocity_controller/pid/d: 0
 * /jaco/jaco_arm_1_joint_velocity_controller/pid/i: 0
 * /jaco/jaco_arm_1_joint_velocity_controller/pid/p: 0.4
 * /jaco/jaco_arm_1_joint_velocity_controller/type: velocity_controll...
 * /jaco/jaco_arm_2_joint_position_controller/joint: jaco_arm_2_joint
 * /jaco/jaco_arm_2_joint_position_controller/pid/d: 0
 * /jaco/jaco_arm_2_joint_position_controller/pid/i: 1.0
 * /jaco/jaco_arm_2_joint_position_controller/pid/p: 20
 * /jaco/jaco_arm_2_joint_position_controller/type: position_controll...
 * /jaco/jaco_arm_2_joint_velocity_controller/joint: jaco_arm_2_joint
 * /jaco/jaco_arm_2_joint_velocity_controller/pid/d: 0
 * /jaco/jaco_arm_2_joint_velocity_controller/pid/i: 0
 * /jaco/jaco_arm_2_joint_velocity_controller/pid/p: 0.4
 * /jaco/jaco_arm_2_joint_velocity_controller/type: velocity_controll...
 * /jaco/jaco_arm_3_joint_position_controller/joint: jaco_arm_3_joint
 * /jaco/jaco_arm_3_joint_position_controller/pid/d: 0
 * /jaco/jaco_arm_3_joint_position_controller/pid/i: 1.0
 * /jaco/jaco_arm_3_joint_position_controller/pid/p: 20
 * /jaco/jaco_arm_3_joint_position_controller/type: position_controll...
 * /jaco/jaco_arm_3_joint_velocity_controller/joint: jaco_arm_3_joint
 * /jaco/jaco_arm_3_joint_velocity_controller/pid/d: 0
 * /jaco/jaco_arm_3_joint_velocity_controller/pid/i: 0
 * /jaco/jaco_arm_3_joint_velocity_controller/pid/p: 0.4
 * /jaco/jaco_arm_3_joint_velocity_controller/type: velocity_controll...
 * /jaco/jaco_arm_4_joint_position_controller/joint: jaco_arm_4_joint
 * /jaco/jaco_arm_4_joint_position_controller/pid/d: 0
 * /jaco/jaco_arm_4_joint_position_controller/pid/i: 1.0
 * /jaco/jaco_arm_4_joint_position_controller/pid/p: 20
 * /jaco/jaco_arm_4_joint_position_controller/type: position_controll...
 * /jaco/jaco_arm_4_joint_velocity_controller/joint: jaco_arm_4_joint
 * /jaco/jaco_arm_4_joint_velocity_controller/pid/d: 0
 * /jaco/jaco_arm_4_joint_velocity_controller/pid/i: 0
 * /jaco/jaco_arm_4_joint_velocity_controller/pid/p: 0.4
 * /jaco/jaco_arm_4_joint_velocity_controller/type: velocity_controll...
 * /jaco/jaco_arm_5_joint_position_controller/joint: jaco_arm_5_joint
 * /jaco/jaco_arm_5_joint_position_controller/pid/d: 0
 * /jaco/jaco_arm_5_joint_position_controller/pid/i: 1.0
 * /jaco/jaco_arm_5_joint_position_controller/pid/p: 20
 * /jaco/jaco_arm_5_joint_position_controller/type: position_controll...
 * /jaco/jaco_arm_5_joint_velocity_controller/joint: jaco_arm_5_joint
 * /jaco/jaco_arm_5_joint_velocity_controller/pid/d: 0
 * /jaco/jaco_arm_5_joint_velocity_controller/pid/i: 0
 * /jaco/jaco_arm_5_joint_velocity_controller/pid/p: 0.4
 * /jaco/jaco_arm_5_joint_velocity_controller/type: velocity_controll...
 * /jaco/jaco_finger_joint_0_position_controller/joint: jaco_finger_joint_0
 * /jaco/jaco_finger_joint_0_position_controller/pid/d: 0
 * /jaco/jaco_finger_joint_0_position_controller/pid/i: 1.0
 * /jaco/jaco_finger_joint_0_position_controller/pid/p: 20
 * /jaco/jaco_finger_joint_0_position_controller/type: position_controll...
 * /jaco/jaco_finger_joint_0_velocity_controller/joint: jaco_finger_joint_0
 * /jaco/jaco_finger_joint_0_velocity_controller/pid/d: 0
 * /jaco/jaco_finger_joint_0_velocity_controller/pid/i: 0
 * /jaco/jaco_finger_joint_0_velocity_controller/pid/p: 0.4
 * /jaco/jaco_finger_joint_0_velocity_controller/type: velocity_controll...
 * /jaco/jaco_finger_joint_2_position_controller/joint: jaco_finger_joint_2
 * /jaco/jaco_finger_joint_2_position_controller/pid/d: 0
 * /jaco/jaco_finger_joint_2_position_controller/pid/i: 1.0
 * /jaco/jaco_finger_joint_2_position_controller/pid/p: 20
 * /jaco/jaco_finger_joint_2_position_controller/type: position_controll...
 * /jaco/jaco_finger_joint_2_velocity_controller/joint: jaco_finger_joint_2
 * /jaco/jaco_finger_joint_2_velocity_controller/pid/d: 0
 * /jaco/jaco_finger_joint_2_velocity_controller/pid/i: 0
 * /jaco/jaco_finger_joint_2_velocity_controller/pid/p: 0.4
 * /jaco/jaco_finger_joint_2_velocity_controller/type: velocity_controll...
 * /jaco/jaco_finger_joint_4_position_controller/joint: jaco_finger_joint_4
 * /jaco/jaco_finger_joint_4_position_controller/pid/d: 0
 * /jaco/jaco_finger_joint_4_position_controller/pid/i: 1.0
 * /jaco/jaco_finger_joint_4_position_controller/pid/p: 20
 * /jaco/jaco_finger_joint_4_position_controller/type: position_controll...
 * /jaco/jaco_finger_joint_4_velocity_controller/joint: jaco_finger_joint_4
 * /jaco/jaco_finger_joint_4_velocity_controller/pid/d: 0
 * /jaco/jaco_finger_joint_4_velocity_controller/pid/i: 0
 * /jaco/jaco_finger_joint_4_velocity_controller/pid/p: 0.4
 * /jaco/jaco_finger_joint_4_velocity_controller/type: velocity_controll...
 * /jaco/joint_state_controller/publish_rate: 100
 * /jaco/joint_state_controller/type: joint_state_contr...
 * /jaco/palm_link: jaco_6_hand_limb
 * /jaco_trajectory/action_topic: /jaco/joint_traje...
 * /jaco_trajectory/angle_safety_limit: -1.0
 * /jaco_trajectory/exceed_duration_wait_factor: 2
 * /jaco_trajectory/goal_angles_intermediate_tolerance: 0.03
 * /jaco_trajectory/goal_angles_tolerance: 0.015
 * /jaco_trajectory/joint_states_topic: /jaco/joint_states
 * /jaco_trajectory/use_angle_poses: True
 * /jaco_trajectory/use_online_control: False
 * /joint_state_control_topic: jaco/joint_control
 * /preserve_original_angles: jaco_arm_1_joint,...
 * /publish_joint_states_topic: jaco/joint_state
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 100.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [1429]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 2f184b26-3311-11e8-ba25-484d7ea4dbcf
process[rosout-1]: started with pid [1442]
started core service [/rosout]
process[gazebo-2]: started with pid [1469]
process[gazebo_gui-3]: started with pid [1476]
process[urdf_spawner-4]: started with pid [1480]
process[robot_state_publisher-5]: started with pid [1482]
[ INFO] [1522300954.617447272]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1522300954.617812221]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1522300954.623526384]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1522300954.623699493]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1522300956.383025320, 0.024000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1522300956.443383772, 0.083000000]: Physics dynamic reconfigure ready.
[ INFO] [1522300956.626582242, 0.260000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1522300956.846119553, 0.310000000]: Physics dynamic reconfigure ready.
[ INFO] [1522300956.892458881, 0.310000000]: Creating GazeboJointControl plugin
[ INFO] [1522300956.892494372, 0.310000000]: Creating GazeboJointControlLocalImpl plugin
[ INFO] [1522300956.893470611, 0.310000000]: Gazebo using SetVelocity(): 1
[ INFO] [1522300956.893503998, 0.310000000]: Loading GazeboJointControl
[ INFO] [1522300956.893558068, 0.310000000]: GazeboJointControl: Loading arm component parameters from jaco
[ INFO] [1522300956.893747956, 0.310000000]: ArmComponentsNameManager reading parameters from namespace: /jaco
[ INFO] [1522300956.901199667, 0.310000000]: INFO: Parameter arm_effort_controller_names has not been specified
[ INFO] [1522300956.907262135, 0.310000000]: INFO: Parameter gripper_effort_controller_names has not been specified
[ INFO] [1522300956.907296863, 0.310000000]: GazeboJointControl: Arm component parameters loaded.
[ INFO] [1522300956.908865800, 0.310000000]: Set to load velocity controlers: 1
[ INFO] [1522300956.909963887, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.912623471, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.914435761, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.916228976, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.918060900, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.919843304, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.921691325, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.923385455, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.924703114, 0.310000000]: Setting fmax prints a warning/error but it somehow still is required...
**[Err] [ODEJoint.cc:515] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast**
[ INFO] [1522300956.926634623, 0.310000000]: GazeboJointControl loaded.
[ INFO] [1522300956.931606734, 0.310000000]: Creating GazeboJointStateClient plugin
[ INFO] [1522300956.933207004, 0.310000000]: GazeboJointStateClient subscription topic: jaco/joint_control
[ INFO] [1522300956.933283030, 0.310000000]: GazeboJointStateClient: Loading arm component parameters from jaco
[ INFO] [1522300956.933392528, 0.310000000]: ArmComponentsNameManager reading parameters from namespace: /jaco
[ INFO] [1522300956.940185307, 0.310000000]: INFO: Parameter arm_effort_controller_names has not been specified
[ INFO] [1522300956.945620999, 0.310000000]: INFO: Parameter gripper_effort_controller_names has not been specified
[ INFO] [1522300956.945887729, 0.310000000]: Gazebo joint: 'jaco_arm_0_joint' is registered as 'jaco_on_table::jaco_arm_0_joint'
[ INFO] [1522300956.945931081, 0.310000000]: Gazebo joint: 'jaco_arm_1_joint' is registered as 'jaco_on_table::jaco_arm_1_joint'
[ INFO] [1522300956.945948711, 0.310000000]: Gazebo joint: 'jaco_arm_2_joint' is registered as 'jaco_on_table::jaco_arm_2_joint'
[ INFO] [1522300956.945965155, 0.310000000]: Gazebo joint: 'jaco_arm_3_joint' is registered as 'jaco_on_table::jaco_arm_3_joint'
[ INFO] [1522300956.945990129, 0.310000000]: Gazebo joint: 'jaco_arm_4_joint' is registered as 'jaco_on_table::jaco_arm_4_joint'
[ INFO] [1522300956.946017147, 0.310000000]: Gazebo joint: 'jaco_arm_5_joint' is registered as 'jaco_on_table::jaco_arm_5_joint'
[ INFO] [1522300956.946044983, 0.310000000]: Gazebo joint: 'jaco_finger_joint_0' is registered as 'jaco_on_table::jaco_finger_joint_0'
[ INFO] [1522300956.946073523, 0.310000000]: Gazebo joint: 'jaco_finger_joint_2' is registered as 'jaco_on_table::jaco_finger_joint_2'
[ INFO] [1522300956.946099940, 0.310000000]: Gazebo joint: 'jaco_finger_joint_4' is registered as 'jaco_on_table::jaco_finger_joint_4'
[ INFO] [1522300956.954853293, 0.310000000]: Creating GazeboJointStatePublisher plugin
[ INFO] [1522300956.956328960, 0.310000000]: Joint state publish topic: jaco/joint_state
[ INFO] [1522300956.958319949, 0.310000000]: Joints to *not* cap to [-PI,PI] in GazeboJointStatePublisher:
[ INFO] [1522300956.958406177, 0.310000000]: jaco_arm_1_joint
[ INFO] [1522300956.958448646, 0.310000000]: jaco_arm_2_joint
[ INFO] [1522300956.958538120, 0.310000000]: GazeboJointStatePublisher: Loading arm component parameters from jaco
[ INFO] [1522300956.958629361, 0.310000000]: ArmComponentsNameManager reading parameters from namespace: /jaco
[ INFO] [1522300956.966328642, 0.310000000]: INFO: Parameter arm_effort_controller_names has not been specified
[ INFO] [1522300956.971544025, 0.310000000]: INFO: Parameter gripper_effort_controller_names has not been specified
[ INFO] [1522300956.982901223, 0.310000000]: Creating GazeboJointTrajectoryServer plugin
[ INFO] [1522300956.982928517, 0.310000000]: Loading GazeboJointTrajectoryServer
[ INFO] [1522300956.983058013, 0.310000000]: GazeboJointTrajectoryServer: Creating trajectory action server, reading ROS parameters from namespaces jaco_trajectory and jaco
[ INFO] [1522300956.983104096, 0.310000000]: ArmComponentsNameManager reading parameters from namespace: /jaco
[ INFO] [1522300956.990586655, 0.310000000]: INFO: Parameter arm_effort_controller_names has not been specified
[ INFO] [1522300956.996172250, 0.310000000]: INFO: Parameter gripper_effort_controller_names has not been specified
[ INFO] [1522300956.996290852, 0.310000000]: Reading joint trajectory parameters from namespace jaco_trajectory
[ INFO] [1522300956.997653948, 0.310000000]: Joint trajectory action topic name: </jaco/joint_trajectory_action>
[ INFO] [1522300956.999012459, 0.310000000]: Goal angles tolerance: <0.015000>
[ INFO] [1522300957.000357121, 0.310000000]: Intermediate goal angles tolerance: <0.030000>
[ INFO] [1522300957.001901730, 0.310000000]: Trajectory goal angles safety limit: <-1.000000>
[ INFO] [1522300957.003160877, 0.310000000]: Using trajectory position mode: <1>
[ INFO] [1522300957.004669528, 0.310000000]: Using online control: <0>
[ INFO] [1522300957.006142515, 0.310000000]: Exceed duration wait factor: <2.000000>
[ INFO] [1522300957.006316732, 0.310000000]: Max velocity for joint jaco_arm_0_joint specified as 0.8
[ INFO] [1522300957.006362524, 0.310000000]: Max velocity for joint jaco_arm_1_joint specified as 0.8
[ INFO] [1522300957.006384892, 0.310000000]: Max velocity for joint jaco_arm_2_joint specified as 0.8
[ INFO] [1522300957.006405690, 0.310000000]: Max velocity for joint jaco_arm_3_joint specified as 0.8
[ INFO] [1522300957.006427251, 0.310000000]: Max velocity for joint jaco_arm_4_joint specified as 0.8
[ INFO] [1522300957.006449134, 0.310000000]: Max velocity for joint jaco_arm_5_joint specified as 0.8
[ INFO] [1522300957.006470628, 0.310000000]: Max velocity for joint jaco_finger_joint_0 specified as 0.3
[ INFO] [1522300957.006491795, 0.310000000]: Max velocity for joint jaco_finger_joint_2 specified as 0.3
[ INFO] [1522300957.006511000, 0.310000000]: Max velocity for joint jaco_finger_joint_4 specified as 0.3
[ INFO] [1522300957.007475161, 0.310000000]: Initializing trajectory action server for 9 joints.
[urdf_spawner-4] process has finished cleanly
log file: /home/user/.ros/log/2f184b26-3311-11e8-ba25-484d7ea4dbcf/urdf_spawner-4*.log
[ INFO] [1522300957.027841132, 0.310000000]: Action server for Joint Trajectory started. Using position mode: 1
[ INFO] [1522300957.027879395, 0.310000000]: Joint trajectory action server running.
**[FATAL] [1522300957.030986631, 0.311000000]: Only support 1 axis
gzserver: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Aborted (core dumped)**
[gazebo-2] process has died [pid 1469, exit code 134, cmd /home/user/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -e ode -s libgazebo_world_plugin_loader.so worlds/empty.world __name:=gazebo __log:=/home/user/.ros/log/2f184b26-3311-11e8-ba25-484d7ea4dbcf/gazebo-2.log].
log file: /home/user/.ros/log/2f184b26-3311-11e8-ba25-484d7ea4dbcf/gazebo-2*.log
[gazebo_gui-3] process has finished cleanly
log file: /home/user/.ros/log/2f184b26-3311-11e8-ba25-484d7ea4dbcf/gazebo_gui-3*.log

I'm using Ubuntu 16.04.4 LTS, ROS Kinetic,  and python 2.7.14. And there is no problem load the model without controllers.

**Comment by HailinRen** [comment]
+1

**Comment by JenniferBuehler** [comment]
Hm strange, I can't reproduce it on Kinetic, it works for me. Maybe the reason is that I have recently upgraded moveit-pkgs for Kinetic, which you also must have fixed up for compiling with Kinetic? Can you please pull the new version of moveit-pkgs, re-compile and try again?

@HailinRen I am still using ``--inorder`` for xacro by the way and it's fine.

There are two possibilities where the error can come from (the error "Only support 1 axis" is the key), and I have altered both of them to not exit the program any more, and instead print a more descriptive error. The fact that your joints are loaded with more than 1 (or 0) axis is weird... anyway, can you please pull joint-control-pkgs and moveit-pkgs again, and then send me the output which should now instead print errors? I need to know the error which is repeatedly printed (about the 1 axis), that's all. Thanks!

**Comment by HailinRen** [comment]
Hi Jennifer,

After I installed the moveit-pkgs, it worked but with one annoying error considering "base_to_jaco_on_table"
so I modified a liitle bit as following.
`if (joint->GetAngleCount() != 1)
        {
            if(_jointName!="base_to_jaco_on_table")
            {
            	 ROS_ERROR_STREAM("GazeboJointStatePublisher: Only support 1 axis, "
                    << "got " << joint->GetAngleCount()
                    << ", cannot write angle for joint '" << _jointName << "'");
            }
            js.name.push_back(_jointName);
            js.position.push_back(0);
            js.velocity.push_back(0);
            js.effort.push_back(0);
            continue;
        }`
Thank you!

**Comment by JenniferBuehler** [comment]
Hi,

thanks for your response. The annyoing error was on purpose, I put it in there so you could send me the output so I'd know where the error comes from ;) Anyway, someone else reported it [here](https://github.com/JenniferBuehler/grasp-execution-pkgs/issues/8#issuecomment-377697890), so I think I know what the issue is now, it's about the fixed joints. 

I have updated joint-control-pkgs, can you please pull it again and confirm that it now works? Thanks!

**Comment by JenniferBuehler** [comment]
Since I haven't heard back, I presume you are not testing this any more.
I'm closing this for now. If you or anybody else has that issue, please re-open this.
