### ISSUE TITLE
catkin_make fails due to CMake Error - Error evaluating generator expression

### ISSUE THREAD

**Issue by HappySamuel** [JenniferBuehler/jaco-arm-pkgs#19]
Hi Jennifer,

I previously successfully installed this package with gazebo7 on ubuntu16.04 with ros-kinetic. However, i just upgraded the gazebo from 7.0 to 9.0. And i found the following issues when i redo the catkin_make:

![screenshot from 2019-03-05 23-03-25](https://user-images.githubusercontent.com/18137963/53814639-ee7a0b80-3f9a-11e9-9c16-f2c3d58f1fdf.png)

I have 3 of them (libprotobuf, ignition-math4 & ignition-common1) installed, but the errors still pop out and caused the catkin_make failed. For other packages (common-sensors, convenience-pkgs, gazebo-pkgs, general-message-pkgs, graspit-pkgs, joint-control-pkgs, moveit-pkgs & urdf-tools-pkgs) are all can be successfully catkin_make.

Can you guide me how to solve this problems?

Best regards.
Samuel

**Comment by JenniferBuehler** [comment]
Hi Samuel,

yes I've had the same thing happen, but when I ran catkin_make again, it resolved itself. It must be the message generation dependency of Gazebo. I haven't gotten around to fix this yet, but it can be resolved by just re-building - or does that not work for you?

Cheers
Jenny

**Comment by HappySamuel** [comment]
Hi Jennifer,

I tried as you said. Well the errors pop out, but i keep going to redo and redo catkin_make, and it suddenly success. Seems like the solution is:
keep on redo catkin_make until success.

Thank you very much.
Samuel

**Comment by JenniferBuehler** [comment]
Yes it's pretty bad, it will have to be fixed. I'll keep this issue open as a reminder that I have to do it ;)

**Comment by HappySamuel** [comment]
Hi @JenniferBuehler 

Recently, I got a chance to re-install this package, and here's my findings on the errors mentioned before.
It's caused by the both **jaco_gazebo** & **grasp_execution_jaco_tutorial** packages.

For the **jaco_gazebo** package, it's caused by both **CMakeLists.txt** and **package.xml**. Here i attached the pictures that i did the modification on both of them in jaco_gazebo package, which eventually remove the errors above.
![Screenshot from 2019-04-25 15-23-09](https://user-images.githubusercontent.com/18137963/56716964-29fcaf00-676e-11e9-92cb-81aef307500d.png) 
![Screenshot from 2019-04-25 15-22-52](https://user-images.githubusercontent.com/18137963/56717063-70520e00-676e-11e9-8088-e39b2a022dc6.png)

For the **grasp_execution_jaco_tutorial** package, it's caused by its **CMakeLists.txt** and **package.xml** too. Here i also attached the pictures that the modification i did on them and eventually errors disappear.
![Screenshot from 2019-04-25 15-48-53](https://user-images.githubusercontent.com/18137963/56718699-d4c29c80-6771-11e9-83a5-3e5d8ee9c3f0.png)
![Screenshot from 2019-04-25 15-48-38](https://user-images.githubusercontent.com/18137963/56718701-d55b3300-6771-11e9-91d8-7b76fff64265.png)

I found these errors after comparing them with kinova_gazebo package, which doesn't have this error in Gazebo 9. So i did modifications to 4 of them, then the errors gone magically. However, i have no idea whether my way of amendment is correct or not. Hope you can test it out and let me know whether they can be modified like above.

Besides, when i look clearly into the catkin_make progress, i found that these packages are giving warning as below:
![Screenshot from 2019-04-25 15-52-35](https://user-images.githubusercontent.com/18137963/56721559-ba8bbd00-6777-11e9-85cf-8075e148dbd3.png)
They are **gazebo_grasp_plugin**, **gazebo_version_helpers** and **gazebo_joint_control**. 
Is there a way to make them use gazebo9 and gazebo9_ros, instead of gazebo and gazebo_ros?


Best,
Samuel

**Comment by JenniferBuehler** [comment]
Hi Samuel,

thanks for looking into this. Indeed, the gazebo_grasp_plugin and gazebo_joint_control packages are not needed as compile-time dependencies any more. The changes you've made should be fine. I will test it next time I boot up melodic.

As for the warning: this means the `find_package(gazebo...)` hasn't worked properly, which it should have (also with version 9)... If you change it to `find_package(gazebo 9 REQUIRED)`, does the warning go away?
I'll double check on this too next time I reboot into melodic.

**Comment by HappySamuel** [comment]
Hi @JenniferBuehler 

Yes i tried with using **find_package(gazebo 9 REQUIRED)**,  for this portion it could find the gazebo 9. but i have no idea with another portion, how should make it findable. 
![Screenshot from 2019-04-29 10-04-45](https://user-images.githubusercontent.com/18137963/56873715-05068580-6a67-11e9-8849-5d299bf7c88f.png)

As i installed **ros-kinetic-gazebo9-ros**, but i couldn't find the package by just applying **gazebo9_ros**. I tried several combination, but still couldn't get it work. 

By the way, is this situation happened to ROS Melodic too? I thought it's only affecting the ROS Kinetic + Gazebo 9

Best,
Samuel

**Comment by JenniferBuehler** [comment]
Hi Samuel,

yes I meant Kinetic not Melodic, sorry ;)

I've just removed the dependencies in the CMakeLists.txt/package.xml files you posted above and tested, it works. Thanks for looking into this! I have pushed the changes.

As to the warnings (like the one you posted about gazebo 9): as far as I can remember, the `DEPENDS` statements where mainly required for getting it to build properly on Jenkins. I think you can ignore the warnings, if it still all builds.

Do you get any compiler/runtime errors with Gazebo 9, or is this just about the warning?

**Comment by JenniferBuehler** [comment]
This should have been resolved in the meantime. Please re-open if this is still an issue.
