### ISSUE TITLE
C++ code explanation for simple joint trajectory client

### ISSUE THREAD

**Issue by krokomon** [JenniferBuehler/jaco-arm-pkgs#20]
I am quite new in the programming world and  i have been mainly working with python and/or matlab, so c++ is completely unknown to me. I was wondering if you could give an intuition about what is written in the code of simple joint trajectory client?
Any help is welcome.

Thanks and keep up the great work!

**Comment by JenniferBuehler** [comment]
Did you already read [this wiki](https://github.com/JenniferBuehler/jaco-arm-pkgs/wiki/Gazebo-plugins-for-controlling-the-joints) and [this](https://github.com/JenniferBuehler/joint-control-pkgs/wiki/joint_trajectory_execution)?

The trajectory execution basically takes a control_msgs/FollowJointTrajectoryAction message and executes it in Gazebo.

**Comment by krokomon** [comment]
Thank you very much, they were both really helpful!

    Στις Κυριακή, 17 Νοεμβρίου 2019, 2:22:44 μ.μ. EET, ο χρήστης Jennifer Buehler <notifications@github.com> έγραψε:  
 
 
Did you already read this wiki and this?

The trajectory execution basically takes a control_msgs/FollowJointTrajectoryAction message and executes it in Gazebo.

**Comment by JenniferBuehler** [comment]
Glad I could help.
