### ISSUE TITLE
joint_states/effort goes to zero when published a torque using effort_controllers/JointGroupEffortController in Gazebo

### ISSUE THREAD

**Issue by amjack0** [JenniferBuehler/jaco-arm-pkgs#21]
I am using `effort_controllers/JointGroupEffortController` wit ur5 arm in Gazebo. I set up my controller (interface etc) like this,

[UR5 package Link](https://github.com/amjack0/universal_robot_effortController)

My controller yaml looks like this,

`arm_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
   - shoulder_pan_joint
   - shoulder_lift_joint
   - elbow_joint
   - wrist_1_joint
   - wrist_2_joint
   - wrist_3_joint`

I run `roslaunch ur_gazebo ur5.launch` and I can see my controller topic `/arm_controller/command`
So, When I publish `rostopic pub` a desired torque of lets say 60 Nm on effort_controllers/JointGroupEffortController. Then it would go to 60 Nm then goes to Zero and the to 60 Nm and again to zero. 

I checked my `ur5.urdf.xacro` for friction, damping, safety controller and limits. Not sure what's wrong.
I checked your `jaco-arm-pkgs` in which `https://github.com/JenniferBuehler/jaco-arm-pkgs/blob/master/jaco_arm/jaco_description/urdf/jaco.urdf.xacro`

You have written about issue of robot collapses due to damping values ? Do you have the same behavior as I do with `joint_state/Effort` (please see the rqt plot below for behavior)

I plot joint_states/efforts to analyze this issue. This issue is seen for every joint. (In the plot, only shoulder_lift_joint is analyzed.)
Plot of the joint state effort looks like this, [rqt plot](https://raw.githubusercontent.com/amjack0/custom_ros_action_server/master/Screenshot%20from%202020-12-30%2019-28-36.png)

ROS Melodic , 18.04
gazebo-9.0.0
Universal Robot (UR5) `https://github.com/ros-industrial/universal_robot/tree/melodic-devel

**Comment by JenniferBuehler** [comment]
Hi, sorry for the late response. I'm not sure what's happening there... I wouldn't think it's the damping, but couldn't exclude it. Did you try to change the values? Is there any other effect apart from the fluctuations in the values? Does it still work, or does the robot collapse/explode?

**Comment by amjack0** [comment]
Hi @JenniferBuehler , Thanks for the reply. I have fixed the issue and works very good. But I see the fluctuation there in the beginning of the `effort trajectory` but which is not collapsing/exploding the robot. So for now all good !

**Comment by JenniferBuehler** [comment]
Glad to hear it's fixed :) will close this then. Feel free to reopen if required
