### ISSUE TITLE
Problem/Solution when building tha main installation

### ISSUE THREAD

**Issue by Betancourt20** [JenniferBuehler/jaco-arm-pkgs#22]
Hello,
First of all thanks a lot for the work you made for the community. I do not know if you still working on the subject of Jaco control, but I found a small issue in the tutorial, when installing and building the package.
I only succeed to make catkin build of the whole jaco-arm-pkgs if only if I had already installed the package of joint-control-pkgs. 
I do not know if it is normal but I was not highlighted ^^. 

Thanks a lot,

Julio

**Comment by JenniferBuehler** [comment]
Hi,
Thank you for pointing this out! I'll make sure to correct and double check the documentation.
Jennifer

**Comment by JenniferBuehler** [comment]
Hi,
Thank you for pointing this out! I'll make sure to correct and double check the documentation.
Jennifer
