### ISSUE TITLE
[Question]Speed of JointTrajectoryActionServer

### ISSUE THREAD

**Issue by JHeinke** [JenniferBuehler/jaco-arm-pkgs#5]
Hi,

i have a question about the speed of the ActionServer. Why does the "Playing trajectory!" step takes exactly 0.5 seconds. My node runs with a frequency of 25Hz and i want that the robot reaches new goals also with a frequency of 25Hz. I have another robot with an ActionServer and there it works very fine. 

I tried to adjust some parameters but i did not find the right one to change the frequency. Now the robot is moving just step by step but i need a steadily movement. 

I add a full step of the ActionServer: 

```
[ INFO] [1464098028.405922032, 86.014000000]: Received joint trajectory goal, trajectory size
[ INFO] [1464098028.406015300, 86.014000000]: Checking trajectory's validity
[ INFO] [1464098028.406066718, 86.014000000]: Trajectory is eligible for execution, goal accepted
[ INFO] [1464098028.406313120, 86.015000000]: Playing trajectory!
[ INFO] [1464098028.907385189, 86.515000000]: JacoTrajectoryActionServer: Execution of trajectory finished. Success=1
```

My program gets a new pose that it has to reach but with a very small change from the pose before. With this pose i get new joint_values from an inverse kinematik which has to be in the near of the old joint_values. These two joint_value vectors are my new trajectory. 

Maybe it is easier to work with velocities but i only want to test something with the jaco simulation and dont want to write so much new code. 

I hope you can help me

Best regards

Julius

**Comment by JenniferBuehler** [comment]
Hi Julius,

that should not be hard to fix. First let me ensure I understood this correctly: You have a joint trajectory with two points, which are not far from each other (so a small step). So, you keep frequently re-sending 2-point trajectories at each iteration in your loop?
What is the duration specified in-between the two trajectory points, is it 0.5 seconds, or something else?

Jennifer

**Comment by JHeinke** [comment]
Hi Jennifer,

thanks for your help. I solved the problem.... After reading your comment it became clear and i saw that i defined the duration in-between the two points to 0.5s. I changed the value and now it works perfectly. 

Sorry for wasting your time ;) This can be closed. 

Julius

**Comment by JenniferBuehler** [comment]
Hi Julius,

glad you solved it. Just wanted to add one comment: If you are sending small trajectories with only two points, it's probably better to control the arm directly with JointState messages (on topic /jaco/joint_control) from within your loop. You don't need the overhead of a joint trajectory with such small steps, as the execution should be accurate enough at 25Hz (the only exception being joint turns in the wrong direction, which is unlikely at such small steps, and this can only be prevented by using joint velocities anyway).
Let me know if I should give you more details on controlling with JointState messages, that's not detailed in the tutorials.

Regards
Jennifer

**Comment by JHeinke** [comment]
Hi Jennifer,

thank you for your comment. I think, i will try it later. I just tested how much compatible our program is, without changing so much code (specific topics etc.). I do not know if the driver of the UR5 supports direct control with JointStates but i will look into it. 

Thank you very much!

Julius

**Comment by JenniferBuehler** [comment]
Ah ok that makes sense. Good luck with your work!

Jennifer
