### ISSUE TITLE
The fixed joint "base_to_jaco_on_table" appears in the Jaco Gazebo model

### ISSUE THREAD

**Issue by Calmjoy** [JenniferBuehler/jaco-arm-pkgs#8]
Dear Jennifer,

Thank you very much for your kind share of your work. I have learnt a lot from the jaco-arm-pkgs.

Now I am using a jaco2 arm and trying to modify the models in the jaco-arm-pkgs to make it work for the jaco2 arm. When I use `roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch` to launch my jaco2 urdf model, I found the fixed joint "jaco_on_table" appear in the spawned jaco gazebo model, which is not used in my moveit model. The "jaco_on_table" is similar to the joint "base_to_jaco_on_table" in your model.

Could you please tell me how to delete this joint in the gazebo model? Thank you very much~

**Comment by JenniferBuehler** [comment]
Hi,

Thanks, I'm glad to hear my packages have been helpful.

it sounds like you have modified version of the URDF? It's hard for me to tell where it comes from when I don't know what you have modified ;) Maybe do a ``grep jaco_on_table`` over your URDF?

Generally, not all joints that appear with the spawned robot have to be used by MoveIt!. You could have a bit complex robot and only use its pinky finger in MoveIt. That doesn't mean that the rest of the robot won't be spawned in Gazebo though... it should be!

Or if I have misunderstood your question, please clarify and provide a bit more detail.

**Comment by Calmjoy** [comment]
Dear Jennifer, 

Thank you very much for your kind reply.

You are right, I have modified the URDF based on the urdf file from kinova ros package for the jaco version j2n6a300. Please kindly find the urdf structure of my model as following.

**Comment by Calmjoy** [comment]
Dear Jennifer,

Thank you very much for your kind reply.

You are right, I have modified the URDF based on the urdf file from `kinova-ros` package for the jaco version j2n6a300. Please kindly find the urdf structure of my model as following.
```
robot name is: jaco2
---------- Successfully Parsed XML ---------------
root Link: world has 1 child(ren)
    child(1):  robot_base
        child(1):  j2n6a300_link_base
            child(1):  j2n6a300_link_1
                child(1):  j2n6a300_link_2
                    child(1):  j2n6a300_link_3
                        child(1):  j2n6a300_link_4
                            child(1):  j2n6a300_link_5
                                child(1):  j2n6a300_link_6
                                    child(1):  j2n6a300_finger_mount_2
                                    child(2):  j2n6a300_finger_mount_3
                                    child(3):  j2n6a300_finger_1
                                        child(1):  j2n6a300_finger_tip_1
                                    child(4):  j2n6a300_finger_2
                                        child(1):  j2n6a300_finger_tip_2
                                    child(5):  j2n6a300_finger_3
                                        child(1):  j2n6a300_finger_tip_3
                                    child(6):  j2n6a300_finger_mount_1
                                child(2):  j2n6a300_ring_6
                            child(2):  j2n6a300_ring_5
                        child(2):  j2n6a300_ring_4
                    child(2):  j2n6a300_ring_3
                child(2):  j2n6a300_ring_2
            child(2):  j2n6a300_ring_1

```
And I have used the command `roslaunch jaco_on_table jaco_on_table_gazebo_controlled.launch ` to start the gazebo simulation. Please kindly find the `rostopic list` and the `rqt_graph` of the system as following.
```
/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/jaco2/camera1/camera_info
/jaco2/camera1/image_raw
/jaco2/camera1/parameter_descriptions
/jaco2/camera1/parameter_updates
/jaco2/joint_control
/jaco2/joint_trajectory_action/cancel
/jaco2/joint_trajectory_action/feedback
/jaco2/joint_trajectory_action/goal
/jaco2/joint_trajectory_action/result
/jaco2/joint_trajectory_action/status
/joint_states
/rosout
/rosout_agg
/tf
/tf_static
```
![rqtgraph_calmjoy1](https://cloud.githubusercontent.com/assets/8012352/24180271/f95a0854-0eee-11e7-86fb-e5cc7f218aa2.png)

I think all things work well until now. Then I have print the message in the /joint_states topic. In the message we can see the 'base_to_world' joint which is a fixed joint has appeared. 
```
header: 
  seq: 410265
  stamp: 
    secs: 410
    nsecs: 421000000
  frame_id: world
name: ['base_to_world', 'j2n6a300_joint_1', 'j2n6a300_joint_2', 'j2n6a300_joint_3', 'j2n6a300_joint_4', 'j2n6a300_joint_5', 'j2n6a300_joint_6', 'j2n6a300_joint_finger_1', 'j2n6a300_joint_finger_2', 'j2n6a300_joint_finger_3']
position: [-4.0913117338448046e-08, -1.2039098707283813e-05, -0.00041950725977990544, -0.0001722890802291488, 4.148455753583136^C
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
And here is the first several link and joint information in my urdf model which are related to the 'base_to_world' joint.

```
<!--link world -->
  <link name="world"/>
  <!--joint robot_base to world -->
  <joint name="base_to_world" type="fixed">
    <dynamics damping="0.5" friction="0.5"/>
    <limit effort="8" lower="-3.943" upper="0.81" velocity="1.0"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="robot_base"/>
  </joint>
  <!--link robot_base -->
  <link name="robot_base">
    <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0.25"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.25"/>
      <geometry>
        <box size="0.4 0.2 0.5"/>
      </geometry>
      <material name="Red"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.25"/>
      <geometry>
        <box size="0.4 0.2 0.5"/>
      </geometry>
    </collision>
  </link>
  <!--link j2n6a300_link_base-->
  <link name="j2n6a300_link_base">
    <inertial>
      <origin rpy="0 0 1.57079632679" xyz="0 0 0.03"/>
      <mass value="0.2844"/>
      <inertia ixx="0.000174644601419" ixy="0" ixz="0" iyy="0.000174644601419" iyz="0" izz="0.0001842912"/>
    </inertial>
    <visual>
      <origin rpy="0 0 1.57079632679" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jaco2_description/meshes/base.dae"/>
      </geometry>
      <material name="">
        <color rgba="0.65 0.65 0.66 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 1.57079632679" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://jaco2_description/meshes/base.STL"/>
      </geometry>
    </collision>
  </link>
  <!--joint j2n6a300_link_base to robot_base-->
  <joint name="j2n6a300_joint_base" type="fixed">
    <dynamics damping="0.5" friction="0.5"/>
    <limit effort="8" lower="-3.943" upper="0.81" velocity="1.0"/>
    <origin rpy="0 0 0" xyz="0 0 0.5"/>
    <parent link="robot_base"/>
    <child link="j2n6a300_link_base"/>
  </joint> 
```
------
When I run the command `roslaunch jaco_on_table_moveit jaco_on_table_rviz.launch`, an error `[ERROR] [1490149711.383343661, 252.856000000]: Joint 'base_to_world' not found in model 'j2n6a300'` showed up. And the interactive marker has not shown in the rviz. Please kindly find the rostopic list and rqt_graph of the system as following.
```
/attached_collision_object
/clock
/collision_object
/execute_trajectory/cancel
/execute_trajectory/feedback
/execute_trajectory/goal
/execute_trajectory/result
/execute_trajectory/status
/feedback_states
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/jaco2/camera1/camera_info
/jaco2/camera1/image_raw
/jaco2/camera1/parameter_descriptions
/jaco2/camera1/parameter_updates
/jaco2/joint_control
/jaco2/joint_trajectory_action/cancel
/jaco2/joint_trajectory_action/feedback
/jaco2/joint_trajectory_action/goal
/jaco2/joint_trajectory_action/result
/jaco2/joint_trajectory_action/status
/joint_path_command
/joint_states
/joint_trajectory_action/cancel
/joint_trajectory_action/feedback
/joint_trajectory_action/goal
/joint_trajectory_action/result
/joint_trajectory_action/status
/move_group/cancel
/move_group/display_contacts
/move_group/display_planned_path
/move_group/feedback
/move_group/goal
/move_group/monitored_planning_scene
/move_group/ompl/parameter_descriptions
/move_group/ompl/parameter_updates
/move_group/plan_execution/parameter_descriptions
/move_group/plan_execution/parameter_updates
/move_group/planning_scene_monitor/parameter_descriptions
/move_group/planning_scene_monitor/parameter_updates
/move_group/result
/move_group/sense_for_plan/parameter_descriptions
/move_group/sense_for_plan/parameter_updates
/move_group/status
/move_group/trajectory_execution/parameter_descriptions
/move_group/trajectory_execution/parameter_updates
/pickup/cancel
/pickup/feedback
/pickup/goal
/pickup/result
/pickup/status
/place/cancel
/place/feedback
/place/goal
/place/result
/place/status
/planning_scene
/planning_scene_world
/recognized_object_array
/robot_status
/rosout
/rosout_agg
/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/feedback
/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/update
/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/update_full
/rviz_ttl_7818_6795632975141444075/motionplanning_planning_scene_monitor/parameter_descriptions
/rviz_ttl_7818_6795632975141444075/motionplanning_planning_scene_monitor/parameter_updates
/tf
/tf_static
/trajectory_execution_event
```
![rqtgraph_calmjoy](https://cloud.githubusercontent.com/assets/8012352/24180150/34897eb0-0eee-11e7-8d7c-fca050806ad1.png)

Thank you very much for your quick and kind reply again. And there is still something confused in my description, please let me know and I will try my best to provide the information needed. I am looking forward to hearing from you and may you have a nice day!

**Comment by JenniferBuehler** [comment]
Hi,

thanks for posting the info. I am currently on a short holiday and will look at this properly at home as soon as possible. I've only briefly read through this now.. first thought: if it's not in the URDF it could be coming from the arm_components_name_manager or a launch file with a static_transform_publisher, but I'll have to have a closer look to tell for sure.

I will post here as soon as I got around to it, will try asap.

Cheers
Jenny

**Comment by JenniferBuehler** [comment]
Hi,
sorry I didn't get around to look at this before now, it's been very busy.
I'm not quite sure I understand where your problem comes from, joint_states is publishing the base_to_world joint. It would be easier if I could test this myself. Do you have a link to a repository where your files are?
Regards
Jenny

**Comment by JenniferBuehler** [comment]
As I haven't heard back, I'll be closing this. Please re-open if you are still experiencing this issue, or let me know how you fixed it, if you did.
Thanks
Jenny
